.gitignore, vercel.json
**Priority**
- Just add vercel
=> chore: config vercel for CD

src/auth/decorators/public.decorator.ts, src/auth/jwt-auth.guard.ts, src/posts/posts.controller.ts
**Priority**
- create public decorator and use it to make post details public
=> feat: make get post details public

src/posts/posts.service.ts
**Priority**
- Fix Qdrant Not Found error when updating and creating post
- Edit post: replace thumbnail URL
=> Fix Qdrant Not Found error when updating and creating post

prisma/migrations/20250430144304_add_view_count_to_post/migration.sql, prisma/migrations/20250430144925_add_view_count_to_blog/migration.sql, prisma/schema.prisma, src/blog/blog.service.ts, src/blog/dto/response/blog-details.dto.ts, src/blog/dto/response/blog-list-item.dto.ts, src/blog/helpers/blog-mapping.helper.ts, src/posts/posts.service.ts
[Link](https://clc-team-ml4jir1c.atlassian.net/jira/software/projects/SCRUM/boards/1?jql=assignee%20%3D%2063cd432195cff7f585c29425&selectedIssue=SCRUM-254)
**Priority**
- Handle view count for blog and post
=> feat: handle view count for blog and post

prisma/schema.prisma, src/art-generation/art-generation.controller.ts, src/art-generation/dto/request/update-prompt-history.dto.ts, src/art-generation/prompt.service.ts, src/main.ts
**Priority**
- Add an endpoint to update images of a prompt
=> feat: add endpoint to update images of a prompt

package.json, prisma/seed.ts
**Priority**
- add seeding for category
=> feat: seed category

prisma/migrations/20250512175329_make_category_description_required/migration.sql, src/categories/categories-management.service.ts
=> feat(category): make description required

src/user/dto/user-profile.dto.ts, src/user/user.controller.ts, src/user/user.service.ts
(https://clc-team-ml4jir1c.atlassian.net/browse/SCRUM-299)
**Priority**
- Modify user controller, service for handling following, follower logic
=> modify get profile endpoint

src/user/dto/get-user-me.dto.ts, src/user/user.controller.ts, src/user/user.service.ts
**Priority**
- Fix endpoint get user profile for me
=> fix get user profile for me endpoint

src/user/dto/get-user-me.dto.ts, src/user/user.service.ts
=> fix: fix get user profile me returning wrong data

prisma/seed.ts
=> feat: seed blogs

src/posts/dto/response/generate-post-metadata.dto.ts, src/posts/workflow-assist.service.ts
=> feat: modify to resturn category ids as well

src/posts/mapper/posts-explore.mapper.ts, src/posts/posts-explore.service.ts, src/posts/posts.controller.ts
=> feat: add isLikedByCurrentUser for post endpoints

src/blog/blog-explore.service.ts, src/blog/blog-management.service.ts, src/blog/dto/response/blog-details.dto.ts, src/blog/helpers/blog-mapping.helper.ts
=> feat: add isLikedByCurrentUser for blog endpoints

src/auth/jwt-auth.guard.ts, src/blog/blog.controller.ts, src/posts/dto/response/post-list-item.dto.ts, src/posts/posts.controller.ts
=> feat: handle endpoints that could be public or not at the same time

prisma/schema.prisma, src/blog/blog-explore.service.ts, src/blog/blog-management.service.ts, src/blog/blog.controller.ts, src/blog/dto/response/blog-user-info.dto.ts, src/blog/helpers/blog-mapping.helper.ts
add full_name and followers_count and is_following when get blog details (findBlogById)
=> feat(blog): add full_name and followers_count

prisma/migrations/20250531031857_update_report_moderator_and_status/migration.sql, prisma/schema.prisma, src/report/report.service.ts
=> feat: return report resolver

src/blog/dto/response/blog-list-item.dto.ts, src/blog/helpers/blog-mapping.helper.ts
=> fix(blog): get trending blogs not returning content

prisma/migrations/20250527111933_add_prompt_info_to_post/migration.sql, prisma/schema.prisma, src/posts/dto/request/create-post.dto.ts, src/posts/posts-explore.service.ts, src/posts/posts-management.service.ts, src/posts/posts.controller.ts, src/posts/validator/posts-management.validator.ts
=> feat: SCRUM-269 get trending ai posts, modify when create too

prisma/migrations/20250603060140_auto_project_and_auto_post/migration.sql, prisma/migrations/20250603131737_add_user_id_to_platform/migration.sql, prisma/schema.prisma, src/app.module.ts, src/art-generation/art-generation.module.ts, src/auto-post/auto-post-generate.service.ts, src/auto-post/auto-post.module.ts, src/auto-post/auto-post.service.ts, src/auto-post/dto/response/auto-post-details.ts, src/auto-post/enum/auto-post-status.enum.ts, src/auto-project/auto-project-read.service.ts, src/auto-project/auto-project-write.service.ts, src/auto-project/auto-project.controller.ts, src/auto-project/auto-project.module.ts, src/auto-project/dto/request/auto-post-meta.dto.ts, src/auto-project/dto/request/create-project.dto.ts, src/auto-project/dto/request/update-project.dto.ts, src/auto-project/dto/response/auto-project-details.dto.ts, src/auto-project/dto/response/auto-project-list-item.dto.ts, src/auto-project/enum/auto-project-status.enum.ts
=> feat: auto project impl

src/blog/blog-explore.service.ts, src/blog/dto/response/blog-list-item.dto.ts, src/blog/helpers/blog-mapping.helper.ts
=> fix: add missing updated_at for user blogs

.github/workflows/node.yml
=> ci: add docker steps and deploy 

package.json, src/auth/strategies/at.strategy.ts, src/auth/strategies/rt.strategy.ts, src/trending/chat.service.ts, src/trending/dto/response/generated-prompt.dto.ts, src/trending/gemini.service.ts, yarn.lock
fix dup noti and gemini trending prompt (3 promtps)
=> fix dup noti and gemini trenidng prompt

src/user/dto/get-user-me.dto.ts, src/user/dto/user-profile.dto.ts, src/user/user.service.ts
=> feat: add created_at field to UserProfileMeDTO and UserProfileDTO

.github/workflows/node.yml, Dockerfile, src/comment/comment.service.ts, src/common/utils/notification.utils.ts, src/likes/likes.service.ts, src/notification/notification.service.ts, src/posts/posts-management.service.ts
=> refactor: prevent self-notifications in comment and like services

.github/workflows/node.yml
=> fix: increase health check attempts from 15 to 30 for better reliability

.prettierrc, package.json, src/app.module.ts, src/blog/blog-embedding.service.ts, src/blog/blog-explore.service.ts, src/blog/blog-management.service.ts, src/categories/categories-embedding.service.ts, src/categories/categories-management.service.ts, src/categories/categories-search.service.ts, src/categories/categories.controller.ts, src/categories/categories.module.ts, src/categories/dto/request/create-category.dto.ts, src/categories/dto/request/update-category.dto.ts, src/config/embedding.config.ts, src/embedding/embedding.utils.ts, src/posts/posts-embedding.service.ts, src/posts/posts-explore.service.ts, src/posts/posts-management.service.ts, src/posts/workflow-assist.service.ts, yarn.lock
=> feat: use config and refactor category embeddings

src/subscription/subscription.service.ts
=> fix: cannot get subscription info for free tier

.github/workflows/node.disabled, .gitignore, package-lock.json
=> refactor: switch from yarn to npm for dependency management and scripts

.github/workflows/deploy.yml
=> fix: improve deployment script with memory cleanup and backup handling

.github/workflows/deploy.yml, .gitignore
=> fix: increase ai load time

.github/workflows/ci_cd.yml
=> feat: update cd

src/auth/auth.service.ts
=> fix: enhance error handling in AuthService methods

.dockerignore, .github/workflows/ci_cd.yml, Dockerfile, src/likes/dto/request/create-like.dto.ts, src/main.ts
=> feat: add swagger test in ci and temp code to test

src/main.ts, src/notification/notification.gateway.ts
=> feat: update CORS configuration to include additional production URLs

src/auto-post/auto-post.service.ts, src/auto-project/auto-project-read.service.ts, src/auto-project/auto-project.controller.ts, src/blog/blog-explore.service.ts, src/blog/blog.controller.ts, src/common/dto/paginated-response.dto.ts, src/common/helpers/pagination.helper.ts, src/posts/dto/request/get-posts.dto.ts, src/posts/dto/request/search-post.dto.ts, src/posts/dto/response/post-list-item.dto.ts, src/posts/mapper/posts-explore.mapper.ts, src/posts/posts-explore.service.ts, src/posts/posts.controller.ts, src/report/report.service.ts, src/user/user-read.service.ts, src/user/user.controller.ts
=> feat: replace post with get, add paginated response, refactoring

src/app.controller.ts, src/main.ts, src/notification/notification.gateway.ts
=> feat: add debugging for CORS

.github/workflows/ci_cd.yml
=> fix: syntax error

src/art-generation/art-generation.controller.ts, src/art-generation/dto/request/get-prompt-history-query.dto.ts, src/art-generation/prompt.service.ts
=> feat: implement paginated prompt history retrieval

src/auth/facebook/facebook.service.ts
=> fix: rename facebook url base

src/main.ts, src/stripe/stripe.controller.ts
=> feat: enhance Stripe webhook handling with raw body parsing and logging

.github/workflows/ci_cd.yml
=> fix: change time format to 24h, and some perf improvements

.github/workflows/ci_cd.yml
=> refactor: deploy test

src/auto-post/auto-post.scheduler.ts, src/auto-post/dto/auto-post.dto.ts
=> fix: auto post dto

scripts/deleteUser.ts, src/blog/blog-explore.service.ts, src/blog/blog.controller.ts, src/blog/dto/request/user-blogs-query.dto.ts, src/user/user.admin.service.ts
**Priority**
1. Fix delete user doesn't delete followers, following count: 
Before deleting user: 
Comments: 
After:
=> feat: add user blogs query DTO and update blog retrieval by username

src/collection/collection.controller.ts, src/collection/collection.service.ts
=> feat: add get collection by username endpoint

src/posts/dto/request/update-post.dto.ts
=> [Tu ]fix: update update post dto

prisma/migrations/20250729012739_remove_fb_account_picture_url/migration.sql, prisma/schema.prisma, src/auth/auth.module.ts, src/auth/facebook/facebook.controller.ts, src/auth/facebook/facebook.service.ts, src/auth/facebook/facebook.type.ts, src/facebook-api/facebook-api.service.ts, src/facebook-api/facebook-api/facebook-api.module.ts, src/generated/client.ts, src/generated/internal/prismaNamespace.ts, src/generated/models/FacebookAccount.ts, src/platform/platform.module.ts, src/platform/platform.service.ts
=> [Tu] Fix/platform picture url

src/blog/blog-explore.service.ts, src/mock.ts
=> fix: SCRUM-521 search blog should not return non public

src/blog/blog-management.service.ts
=> feat: uncomment calls to qdrant

src/auto-post/auto-post-generate-v2.service.ts
=> fix: update prompt generate with more precise word count

prisma/migrations/20250802093225_update_auto_project_status/migration.sql, prisma/schema.prisma, src/auto-post/auto-post.service.ts, src/auto-project/auto-project-write.service.ts, src/auto-project/auto-project.controller.ts, src/generated/enums.ts
=> [Tu] Fix/start auto project

src/auto-post/auto-post-generate-v2.service.ts
=> [Tu] Fix/auto post

src/collection/dto/response/post-summary.dto.ts, src/collection/helpers/collection-mapping.helper.ts
=> [Tu] fix: collection card author name is unknown

src/auth/facebook/facebook.service.ts
=> fix(facebook): remove unnecessary permissions from OAuth scopes

src/posts/dto/response/post-details-view.dto.ts, src/posts/posts-explore.service.ts
=> [Tu] fix: add categories to post details view return data
